### ISSUE TITLE
Board class refinements.

### ISSUE THREAD

**Issue by Montessquio** [Montessquio/hide-and-seek-se300#5]
As I said in #4, This does need some re-working. Exception messages could be pared down, and the files could use some grammar clean-up.

There's also no clean API for getting the state of the board, since having to loop through the whole board and manually call IsOpenSpace() or other methods is tedious.

This is the tracking issue for this task.

**Comment by mjliepke** [comment]
I just realized that I didn't give the manager direct access into the board's state.  Could this be implemented by a simple GetBoard() function in the Board class, or perhaps making the board have a public read access?

**Comment by Montessquio** [comment]
Since the current sprint simply requires an empty board with two actors, I simply changed the AgentLocation function into two functions of their own: 

```csharp
        public static (int, int) GetHiderLocation(Board board)
        {
            for (int i = 0; i < board.boardSize; i++)
            {
                for (int j = 0; j < board.boardSize; j++)
                {
                    if (board.board[i, j] == BoardStates.Hider)
                    {
                        return (i, j);
                    }
                }
            }

            throw new GameException("No Hiders on the Board!");
        }

        public static (int, int) GetSeekerLocation(Board board)
        {
            for (int i = 0; i < board.boardSize; i++)
            {
                for (int j = 0; j < board.boardSize; j++)
                {
                    if (board.board[i, j] == BoardStates.Seeker)
                    {
                        return (i, j);
                    }
                }
            }

            throw new GameException("No Seekers on the Board!");
        }
```

I felt this satisfied your requirement for it only to be called on those actors and wasn't too intrusive.

---

As for the issue regarding the board, a simple enumerator of all board tiles and their coordinates would work just fine. Something like this would be fine:

```csharp
foreach(int x, int y, BoardStates state) {
    // Do something with each tile in the renderer
}
```

**Comment by mjliepke** [comment]
This Issue's resolution is causing more problems.  By defining a function per agent instead of one more abstract function with all the functionality, it is requiring more code to be built to facilitate this binary approach.  If I don't know the agent who I am searching for I cannot find the agent's location.  In addition, the return modified return case of a variable is bad coding practice and doesn't allow for explicit 

>   
        private Board GetAgentVisionBoard(Agent agent)
        {
            int[] myCoords;
            if(agent.WhoAmI() == BoardStates.Seeker)
            {
                var(x, y) = Board.GetSeekerLocation(board);
                myCoords = new int[] { x, y };
            }
            else
            {
                var(x,y) = Board.GetHiderLocation(board);
                myCoords = new int[] { x, y };
            }
            //Do something
            
        }
>
This would be a one-liner if the return type was explicitly typed and the function allowed abstract in that it allowed any agent to be found.
